import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/ui/haeder";
import Footer from "@/components/ui/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className="flex flex-col items-center"
      >
        <div className="w-[85%] flex flex-col">
        <Header />
        {children}
        <Footer />
        </div>

      </body>
    </html>
  );
}
